services:
  web-db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: web

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
