spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:mem:web-db
    username: sa
    password: admin

  banner:
    location: banner.txt

server:
  port: 8081

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000
